[package]
name = "null-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
null-core = { workspace = true }
x25519-dalek = { version = "2", features = ["static_secrets"] }
curve25519-dalek = "4"
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
sha3 = "0.10"
ml-kem = { version = "0.2", features = ["deterministic"] }
kem = "0.3.0-pre.0"
hybrid-array = "0.2"
ml-dsa = "0.1"
zeroize.workspace = true
rand.workspace = true
rand_core.workspace = true
thiserror.workspace = true
serde.workspace = true
